apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kyma-config
spec:
    replicas: 1
    selector:
        matchLabels:
        app: hello-kyma-config
    template:
        metadata:
        labels:
            app: hello-kyma-config
        spec:
        containers:
        - name: my-container
            image: my-image
            envFrom: # 1. Use all keys as environment variables
            - configMapRef:
                name: my-config
            env: # 2. Use only specific keys as environment variables
            - name: MY_KEY
                valueFrom:
                configMapKeyRef:
                    name: my-config
                    key: my-key